global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "skillmaster-api"
    static_configs:
      - targets: ["api:8000"]
  - job_name: "skillmaster-bff"
    static_configs:
      - targets: ["bff:4000"]
